// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: reddit/reddit_feed_api/v1/reddit_feed_api.proto

/*
Package reddit_feed_api is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package reddit_feed_api

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/grpclog"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

var (
	filter_RedditFeedAPIService_CreatePostsV1_0 = &utilities.DoubleArray{Encoding: map[string]int{}, Base: []int(nil), Check: []int(nil)}
)

func request_RedditFeedAPIService_CreatePostsV1_0(ctx context.Context, marshaler runtime.Marshaler, client RedditFeedAPIServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreatePostsV1Request
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_RedditFeedAPIService_CreatePostsV1_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := client.CreatePostsV1(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_RedditFeedAPIService_CreatePostsV1_0(ctx context.Context, marshaler runtime.Marshaler, server RedditFeedAPIServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq CreatePostsV1Request
	var metadata runtime.ServerMetadata

	if err := req.ParseForm(); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}
	if err := runtime.PopulateQueryParameters(&protoReq, req.Form, filter_RedditFeedAPIService_CreatePostsV1_0); err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "%v", err)
	}

	msg, err := server.CreatePostsV1(ctx, &protoReq)
	return msg, metadata, err

}

func request_RedditFeedAPIService_GenerateFeedV1_0(ctx context.Context, marshaler runtime.Marshaler, client RedditFeedAPIServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GenerateFeedV1Request
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["page_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "page_id")
	}

	protoReq.PageId, err = runtime.Uint64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "page_id", err)
	}

	msg, err := client.GenerateFeedV1(ctx, &protoReq, grpc.Header(&metadata.HeaderMD), grpc.Trailer(&metadata.TrailerMD))
	return msg, metadata, err

}

func local_request_RedditFeedAPIService_GenerateFeedV1_0(ctx context.Context, marshaler runtime.Marshaler, server RedditFeedAPIServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	var protoReq GenerateFeedV1Request
	var metadata runtime.ServerMetadata

	var (
		val string
		ok  bool
		err error
		_   = err
	)

	val, ok = pathParams["page_id"]
	if !ok {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "missing parameter %s", "page_id")
	}

	protoReq.PageId, err = runtime.Uint64(val)
	if err != nil {
		return nil, metadata, status.Errorf(codes.InvalidArgument, "type mismatch, parameter: %s, error: %v", "page_id", err)
	}

	msg, err := server.GenerateFeedV1(ctx, &protoReq)
	return msg, metadata, err

}

// RegisterRedditFeedAPIServiceHandlerServer registers the http handlers for service RedditFeedAPIService to "mux".
// UnaryRPC     :call RedditFeedAPIServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterRedditFeedAPIServiceHandlerFromEndpoint instead.
func RegisterRedditFeedAPIServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server RedditFeedAPIServiceServer) error {

	mux.Handle("POST", pattern_RedditFeedAPIService_CreatePostsV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/reddit.reddit_feed_api.v1.RedditFeedAPIService/CreatePostsV1", runtime.WithHTTPPathPattern("/v1/posts"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_RedditFeedAPIService_CreatePostsV1_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_RedditFeedAPIService_CreatePostsV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_RedditFeedAPIService_GenerateFeedV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		var stream runtime.ServerTransportStream
		ctx = grpc.NewContextWithServerTransportStream(ctx, &stream)
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateIncomingContext(ctx, mux, req, "/reddit.reddit_feed_api.v1.RedditFeedAPIService/GenerateFeedV1", runtime.WithHTTPPathPattern("/v1/feed/{page_id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := local_request_RedditFeedAPIService_GenerateFeedV1_0(rctx, inboundMarshaler, server, req, pathParams)
		md.HeaderMD, md.TrailerMD = metadata.Join(md.HeaderMD, stream.Header()), metadata.Join(md.TrailerMD, stream.Trailer())
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_RedditFeedAPIService_GenerateFeedV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

// RegisterRedditFeedAPIServiceHandlerFromEndpoint is same as RegisterRedditFeedAPIServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterRedditFeedAPIServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	conn, err := grpc.Dial(endpoint, opts...)
	if err != nil {
		return err
	}
	defer func() {
		if err != nil {
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
			return
		}
		go func() {
			<-ctx.Done()
			if cerr := conn.Close(); cerr != nil {
				grpclog.Infof("Failed to close conn to %s: %v", endpoint, cerr)
			}
		}()
	}()

	return RegisterRedditFeedAPIServiceHandler(ctx, mux, conn)
}

// RegisterRedditFeedAPIServiceHandler registers the http handlers for service RedditFeedAPIService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterRedditFeedAPIServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return RegisterRedditFeedAPIServiceHandlerClient(ctx, mux, NewRedditFeedAPIServiceClient(conn))
}

// RegisterRedditFeedAPIServiceHandlerClient registers the http handlers for service RedditFeedAPIService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "RedditFeedAPIServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "RedditFeedAPIServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "RedditFeedAPIServiceClient" to call the correct interceptors.
func RegisterRedditFeedAPIServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client RedditFeedAPIServiceClient) error {

	mux.Handle("POST", pattern_RedditFeedAPIService_CreatePostsV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/reddit.reddit_feed_api.v1.RedditFeedAPIService/CreatePostsV1", runtime.WithHTTPPathPattern("/v1/posts"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_RedditFeedAPIService_CreatePostsV1_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_RedditFeedAPIService_CreatePostsV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	mux.Handle("GET", pattern_RedditFeedAPIService_GenerateFeedV1_0, func(w http.ResponseWriter, req *http.Request, pathParams map[string]string) {
		ctx, cancel := context.WithCancel(req.Context())
		defer cancel()
		inboundMarshaler, outboundMarshaler := runtime.MarshalerForRequest(mux, req)
		rctx, err := runtime.AnnotateContext(ctx, mux, req, "/reddit.reddit_feed_api.v1.RedditFeedAPIService/GenerateFeedV1", runtime.WithHTTPPathPattern("/v1/feed/{page_id}"))
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}
		resp, md, err := request_RedditFeedAPIService_GenerateFeedV1_0(rctx, inboundMarshaler, client, req, pathParams)
		ctx = runtime.NewServerMetadataContext(ctx, md)
		if err != nil {
			runtime.HTTPError(ctx, mux, outboundMarshaler, w, req, err)
			return
		}

		forward_RedditFeedAPIService_GenerateFeedV1_0(ctx, mux, outboundMarshaler, w, req, resp, mux.GetForwardResponseOptions()...)

	})

	return nil
}

var (
	pattern_RedditFeedAPIService_CreatePostsV1_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1}, []string{"v1", "posts"}, ""))

	pattern_RedditFeedAPIService_GenerateFeedV1_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2}, []string{"v1", "feed", "page_id"}, ""))
)

var (
	forward_RedditFeedAPIService_CreatePostsV1_0 = runtime.ForwardResponseMessage

	forward_RedditFeedAPIService_GenerateFeedV1_0 = runtime.ForwardResponseMessage
)
