project:
  name: Reddit Feed API
  debug: true
  environment: development
  swaggerDir: swagger

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8081

logger:
  level: debug
  encoding: json
  outputPaths:
    - stdout
    - logs.json
  errorOutputPaths:
    - stdout
    - errors.json
  encoderConfig:
    messageKey: message
    levelKey: level
    levelEncoder: lowercase
    timeKey: time
    timeEncoder: iso8601
    callerKey: file
    callerEncoder: file:line

database:
  host: 0.0.0.0
  port: 5432
  user: docker
  password: docker
  name: reddit_feed_api
  sslmode: disable
  driver: pgx

jaeger:
  host: 0.0.0.0
  port: 6831
  service: reddit-feed-api

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

status:
  host: localhost
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  swaggerPath: /swagger/
  versionPath: /version
