project:
  name: Reddit Feed API
  debug: true
  environment: development
  swaggerDir: swagger

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8081

database:
  host: postgres
  port: 5432
  user: docker
  password: docker
  name: reddit_feed_api
  sslmode: disable
  driver: pgx

jaeger:
  host: jaeger
  port: 6831
  service: reddit-feed-api

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

status:
  host: 0.0.0.0
  port: 8003
  livenessPath: /live
  readinessPath: /ready
  swaggerPath: /swagger/
  versionPath: /version

kafka:
  capacity: 512
  topic: "ocp-template-events"
  groupId: "ocp-template-api"
  brokers:
    - "kafka:9092"
    - "localhost:9094"
