project:
  name: Reddit Feed API
  debug: false
  environment: production
  swaggerDir: swagger

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5 # Minutes
  timeout: 15 # Seconds
  maxConnectionAge: 5 # Minutes

rest:
  host: 0.0.0.0
  port: 8081

logger:
  level: info
  encoding: json
  outputPaths:
    - stdout
  errorOutputPaths:
    - stdout
  encoderConfig:
    messageKey: msg
    levelKey: lvl
    levelEncoder: lowercase
    timeKey: time
    timeEncoder: iso8601

database:
  host: postgres
  port: 5432
  user: docker
  password: docker
  name: reddit_feed_api
  sslmode: disable
  driver: pgx

jaeger:
  host: jaeger
  port: 6831
  service: reddit-feed-api

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  swaggerPath: /swagger/
  versionPath: /version
