project:
  name: Reddit Feed API
  debug: false
  environment: production
  swaggerDir: api/openapi-spec

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5m
  timeout: 15s
  maxConnectionAge: 5m

rest:
  host: 0.0.0.0
  port: 8080

database:
  host: postgres
  port: 5432
  user: docker
  password: docker
  name: reddit_feed_api
  sslmode: disable
  migrationsDir: migrations
  driver: pgx

jaeger:
  url: http://jaeger:14268/api/traces
  service: reddit-feed-api

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

logger:
  level: info
  encoding: json
  outputPaths:
    - stdout
  errorOutputPaths:
    - stdout
  encoderConfig:
    messageKey: msg
    levelKey: lvl
    levelEncoder: lowercase
    timeKey: time
    timeEncoder: iso8601

status:
  host: 0.0.0.0
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version
  loggerPath: /log/level
  swaggerDir: api/openapi-spec
  swaggerPath: /swagger/

kafka:
  capacity: 64
  topic: reddit-feed-events
  groupId: reddit-feed-api
  brokers:
    - kafka:9092
    - localhost:9094
