project:
  name: Reddit Feed API
  debug: true
  environment: development
  swaggerDir: api/openapi-spec

grpc:
  host: 0.0.0.0
  port: 8082
  maxConnectionIdle: 5m
  timeout: 15s
  maxConnectionAge: 5m

rest:
  host: 0.0.0.0
  port: 8080

database:
  host: 0.0.0.0
  port: 5432
  user: docker
  password: docker
  name: reddit_feed_api
  sslmode: disable
  migrationsDir: migrations/reddit-feed-api
  driver: pgx

jaeger:
  url: http://localhost:14268/api/traces
  service: reddit-feed-api

metrics:
  host: 0.0.0.0
  port: 9100
  path: /metrics

logger:
  level: debug
  encoding: json
  outputPaths:
    - stdout
    - bin/logs.json
  errorOutputPaths:
    - stdout
    - bin/errors.json
  encoderConfig:
    messageKey: message
    levelKey: level
    levelEncoder: lowercase
    timeKey: time
    timeEncoder: iso8601
    callerKey: file
    callerEncoder: file:line

status:
  host: localhost
  port: 8000
  livenessPath: /live
  readinessPath: /ready
  versionPath: /version
  loggerPath: /log/level
  swaggerDir: api/openapi-spec
  swaggerPath: /swagger/

kafka:
  capacity: 64
  topic: reddit-feed-events
  groupId: reddit-feed-api
  brokers:
    - localhost:9092
