producer:
  capacity: 64
  topic: reddit-feed-events
  brokers:
    - localhost:9092

logger:
  level: debug
  encoding: json
  outputPaths:
    - stdout
  errorOutputPaths:
    - stdout
  encoderConfig:
    messageKey: message
    levelKey: level
    levelEncoder: lowercase
    timeKey: time
    timeEncoder: iso8601
    callerKey: file
    callerEncoder: file:line

posts:
  - author: t2_00000001
  - author: t2_00000002
  - author: t2_00000003
  - author: t2_00000004
  - author: t2_00000005
  - author: t2_00000006
  - author: t2_00000007
  - author: t2_00000008
  - author: t2_00000009
  - author: t2_00000010
  - author: t2_00000011
  - author: t2_00000012
  - author: t2_00000013
  - author: t2_00000014
  - author: t2_00000015
  - author: t2_00000016
